
// ============================================================================
// CORE TYPES & INTERFACES
// ============================================================================

import {
  SelectableElement,
  Coord as SECoord,
  createKeypointElement, 
  createSegmentElement, 
  createPositionElements
} from '../SelectableElement';

export interface Vector3 {
  x: number;
  y: number;
  z: number;
}

export interface Block {
  modelKey: string;
  position: Vector3;
}

export interface GameConfig {
  type: string;
  blocks: Block[];
  players?: Array<{ id: string; start: Vector3 & { direction: number } }>;
  collectibles?: Array<{ id: string; type: string; position: Vector3 }>;
  interactibles?: Array<{ id: string; type: string; position: Vector3 }>;
  finish?: Vector3;
  // [NEW] Optional metadata for composite structures
  metadata?: CompositeMetadata;
}

// Analyzer Options
export interface AnalyzerOptions {
  minLength?: number;
  preferredInterval?: number;
}

// Tier 1 Types
export type GeometricType = 
  | 'point'           // Điểm đặc biệt (junction, center, isolated)
  | 'line_2d'         // Đường thẳng 2D (trên 1 mặt phẳng)
  | 'line_3d'         // Đường thẳng 3D (chéo trong không gian)
  | 'parallel_axis'   // Cặp đường song song + đối xứng trục
  | 'axis_symmetric'  // Đối xứng trục
  | 'perpendicular'   // Vuông góc
  | 'point_symmetric' // Đối xứng tâm
  | 'area'            // Vùng (bounding box hoặc polygon)
  | 'connector';      // Đường nối giữa các vùng (polyline)

export interface PathSegment {
  id: string;
  points: Vector3[];
  direction: Vector3;  // Normalized direction vector
  length: number;
  plane?: 'xy' | 'xz' | 'yz' | '3d';  // Which plane it lies on
}

export interface Area {
  id: string;
  blocks: Vector3[];         // All blocks in this area
  boundary: Vector3[];       // Perimeter blocks (đường bao)
  center: Vector3;           // Centroid
  boundingBox: { min: Vector3; max: Vector3 };
  // NEW: Enhanced area properties from Geometric Reasoning Engine
  dimensions?: { width: number; depth: number };
  shapeType?: 'rectangle' | 'square' | 'irregular';
  holes?: Hole[];            // Internal holes
  gateways?: Gateway[];      // Entry/exit points connecting to paths
  // [NEW] Cấu trúc nội tại
  subStructures?: AreaSubStructure[]; // Internal components (wings, spine)
  internalPaths?: PathSegment[]; // Contour edges (zigzag, base)
}

export interface AreaSubStructure {
  type: 'wing_mass' | 'body_mass';
  id: string;
  coords: Vector3[];
  description?: string;
}

// NEW: Hole in an Area (empty space inside)
export interface Hole {
  id: string;
  coords: Vector3[];         // Coordinates of the hole
  size: number;              // Number of blocks in hole
  isCentered: boolean;       // Is the hole centered in the parent area?
}

// NEW: Gateway - connection point between Path and Area
export interface Gateway {
  id: string;
  coord: Vector3;            // Gateway position
  connectedPathId: string;   // ID of the connected path
  connectedAreaId: string;   // ID of the connected area
  direction: Vector3;        // Direction from path into area
}

// NEW: MetaPath - chain of connected path segments with pattern analysis
export interface MetaPath {
  id: string;
  segments: PathSegment[];   // Ordered list of connected segments
  joints: Vector3[];         // Corner points where direction changes
  structureType: 'straight_chain' | 'macro_staircase' | 'spiral' | 'u_shape' | 'branching' | 'random';
  isRegular: boolean;        // True if segments have equal/pattern lengths
  totalLength: number;
}

export interface Connector {
  id: string;
  fromArea: string;
  toArea: string;
  path: Vector3[];           // Polyline của đường nối
  segments: PathSegment[];   // Các đoạn thẳng tạo nên connector
}

// ============================================================================
// COMPOSITE STRUCTURE TYPES (for Layout × Module architecture)
// ============================================================================

/**
 * Component metadata for sub-structures within a composite topology.
 * Generated by topologies like PlusShapeIslands to describe each island.
 */
export interface ComponentMetadata {
  id: string;                        // e.g., 'island_east', 'island_west'
  module_type: string;               // e.g., 'square', 'triangle', 'arrow_head'
  center: [number, number, number];  // Center position [x, y, z]
  bounds: {
    min_x: number;
    max_x: number;
    min_z: number;
    max_z: number;
  };
  landmarks: Record<string, [number, number, number]>;  // Named positions
}

/**
 * Connector metadata describing bridges between hub and components.
 */
export interface ConnectorMetadata {
  from: string;                      // e.g., 'hub'
  to: string;                        // e.g., 'island_east'
  path: [number, number, number][];  // Bridge path coordinates
}

/**
 * Composite metadata present when topology uses Layout × Module architecture.
 * When this is present in GameConfig metadata, Analyzer should use it
 * instead of pure geometric decomposition.
 */
export interface CompositeMetadata {
  layout_pattern: string;            // e.g., 'radial_4', 'linear_chain', 'grid_2x2'
  components: ComponentMetadata[];
  connectors: ConnectorMetadata[];
  hub?: [number, number, number][];  // Hub points if applicable
  center?: [number, number, number]; // Center point
}

export interface PathRelation {
  type: GeometricType;
  path1Id: string;
  path2Id: string;
  metadata: {
    axis?: Vector3;          // For axis_symmetric
    center?: Vector3;        // For point_symmetric
    distance?: number;       // For parallel
    angle?: number;          // For perpendicular (should be 90)
  };
}

export interface SpecialPoint {
  id: string;
  coord: Vector3;
  type: 'junction' | 'center' | 'endpoint' | 'isolated';
  connectedSegments: string[];
}

// Tier 1 Output
export interface Tier1Result {
  points: SpecialPoint[];
  segments: PathSegment[];
  areas: Area[];
  connectors: Connector[];
  relations: PathRelation[];
  // NEW: From Geometric Reasoning Engine
  metaPaths: MetaPath[];     // Connected path chains with pattern analysis
  gateways: Gateway[];       // Path-Area connection points
}

// Tier 2 Types
export interface Pattern {
  id: string;
  type: 'repeat' | 'mirror' | 'rotate' | 'scale';
  unitElements: string[];    // IDs of segments/areas that form the unit
  repetitions: number;
  transform: {
    translate?: Vector3;
    rotateAxis?: Vector3;
    rotateAngle?: number;
    scale?: number;
    mirrorPlane?: 'xy' | 'xz' | 'yz';
  };
}

export interface Tier2Result extends Tier1Result {
  patterns: Pattern[];
}

// Tier 3 Output (filtered)
export interface Tier3Result extends Tier2Result {
  filteredSegments: PathSegment[];
  mergedSegments: PathSegment[];
  keptShortSegments: PathSegment[];  // Short but kept due to pattern
}

// Prioritized Coordinate (from CoordinatePrioritizer)
export type CoordCategory = 
  | 'critical'      // Must have item (e.g., junction, goal)
  | 'important'     // Should have item (e.g., endpoints, symmetric points)
  | 'recommended'   // Good to have (e.g., regular intervals)
  | 'optional'      // Can have (e.g., filler positions)
  | 'avoid';        // Should NOT have item (e.g., start position, blocked)

export interface PrioritizedCoord {
  position: Vector3;
  priority: number;          // 1-10 (10 = highest priority)
  category: CoordCategory;
  reasons: string[];
  segmentId?: string;
  relatedCoords?: Vector3[]; // Other coords that form a pattern with this one
}

// Map Metrics
export interface MapMetrics {
  totalBlocks: number;
  boundingBox: { width: number; height: number; depth: number };
  area: number;
  estimatedSize: 'tiny' | 'small' | 'medium' | 'large' | 'huge';
  segmentCount: number;
  areaCount: number;
  junctionCount: number;
  longestPathLength: number;
  center: Vector3;
  detectedTopology?: string;
}

// Placement Constraints
export interface PlacementConstraints {
  maxItems: number;
  minItems: number;
  targetItemRatio: number;
  preferredConcepts: string[];
  avoidConcepts: string[];
  maxCodeBlocks: number;
  distribution: 'spread' | 'symmetric' | 'clustered' | 'endpoints' | 'alternating' | 'progressive';
  preferredInterval: number;
}

// Re-export SelectableElement for consumers
export type { SelectableElement, SECoord };
export { createKeypointElement, createSegmentElement, createPositionElements };

// Tier 4 Output (final)
export interface PlacementContext {
  // Tier 1 Core structure
  points: SpecialPoint[];        // Special points (junctions, endpoints, etc.)
  segments: PathSegment[];       // Path segments
  areas: Area[];                 // Connected areas
  connectors: Connector[];       // Connections between areas
  relations: PathRelation[];     // Geometric relations between paths
  
  // NEW: From Geometric Reasoning Engine
  metaPaths: MetaPath[];         // Connected path chains with pattern analysis
  gateways: Gateway[];           // Path-Area connection points
  
  // Tier 2 Patterns
  patterns: Pattern[];
  
  // Prioritized coordinates
  prioritizedCoords: PrioritizedCoord[];
  
  // Map metrics
  metrics: MapMetrics;
  
  // Constraints
  constraints: PlacementConstraints;
  
  // Selectable elements (NEW - for UI selection)
  selectableElements: SelectableElement[];
  
  // Legacy: suggested placements
  suggestedPlacements: Array<{
    segmentId?: string;
    areaId?: string;
    patternId?: string;
    positions: Vector3[];
    itemType: 'crystal' | 'switch' | 'gem' | 'goal';
    rule: string;
  }>;
}
